### ISSUE TITLE
Adding support for valves/faucets

### ISSUE THREAD

**Issue by superjunky** [macjl/Domoticz-HomekitInsecureClient#2]
Hey hello,

I was surprised to find your plugin, I can make great use of it :)

Could you add support for valves and faucets? A simple switch would suffice.
I bet you would need the log line right?
```
Homebridge3: (Homebridge3) Device Miele Washing Machine - AID=62 - Type of Service=D0 - Not supported yet
```

Thanks for sharing your work!

**Comment by macjl** [comment]
Hello. I think it would be easy. I also have valve to test it.
I’ll try to add it this week-end.

**Comment by superjunky** [comment]
Cool, looking forward to the result.

**Comment by macjl** [comment]
Hello,

I've just published a new release.
I've tested it on my sprinkler provided by a Sonoff 4ch Pro with HAA firmware, and seems OK on my side.

**Comment by superjunky** [comment]
Hi! I tried it for my Miele washing machine. It works flawless :)
Thanks for the effort!
