### ISSUE TITLE
 ('Plugin_ASIO')) received fatal signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by JonyBCN** [macjl/Domoticz-HomekitInsecureClient#4]
After a few days with the plugin working without problems, I have noticed that Domoticz was constantly restarting on my raspberry.

The truth is that it was difficult for me to find the error, but after investigating the LOG I have seen this:

**Error: Homekit NAS: (Homekit NAS) Failed to connect (111) to: 192.168.1.99:51824 with error: Connection refused
Error: Domoticz (pid: 21142, tid: 21174 ('Plugin_ASIO')) received fatal signal 11 (Segmentation fault)**

The bug has been fixed by deactivating the plugin, so I am 90% convinced that it is related.

**Comment by macjl** [comment]
Hello,

I had similar issue some times ago. I resolved it by removing some plugins, but not necessarily this one.
I think Domoticz may have issue when having too many plugins. Could you test if deactivating another plugin also resolve your problem ?
And  is your domoticz up-to-date ?

Regards,

**Comment by JonyBCN** [comment]
You are absolutely right. I have disabled some plugins and the operation seems to be correct again. There was an assumption that it was the plugin because it was the last one installed.
 Thank you.
